# Generated by Django 3.1.3 on 2021-03-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hosts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_to_remote_users',
            field=models.ManyToManyField(blank=True, null=True, to='web.HostToRemoteUser'),
        ),
    ]
